- name: Download Microsoft GPG apt Key
  become: true
  get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: "/tmp/microsoft.gpg"

- name: Import Microsoft GPG key
  become: true
  ansible.builtin.shell: |
    gpg --dearmor --yes -o /etc/apt/keyrings/microsoft.gpg /tmp/microsoft.gpg
  changed_when: false

- name: Add Microsoft Repository
  apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present

- name: Install VSCODE
  become: true
  apt:
    name:
      - code
    state: present
